spring.application.name=tp02-di
server.port=8080

# ============================================================
# Exercice 2 - Profils : decommenter la ligne souhaitee
# Aucun profil actif    => EmailService (@Primary) est utilise
# spring.profiles.active=dev    => DevMessageService
# spring.profiles.active=prod   => ProdMessageService
# ============================================================
